name: Build & Deploy Vector Tiles
on:
  push:
    paths:
      - 'fountains.geojson'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe nodejs npm
          npm install -g osmtogeojson

      - name: Convert Overpass JSON to GeoJSON
        run: |
          osmtogeojson fountains.geojson > cleaned.geojson

      - name: Generate MBTiles with Tippecanoe
        run: |
          tippecanoe             -o fountains.mbtiles             --drop-densest-as-needed -Z0 -z16 cleaned.geojson

      - name: Extract PBF Tiles
        run: |
          python3 -m pip install mbutil
          mb-util fountains.mbtiles tiles --image_format=pbf

      - name: Create TileJSON
        run: |
          cat <<EOF > tiles.json
          {
            "tilejson": "2.2.0",
            "name": "fountains",
            "version": "1.0.0",
            "scheme": "xyz",
            "tiles": ["https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/tiles/{z}/{x}/{y}.pbf"]
          }
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
